name: Feature Request
description: Suggest an idea for this project
title: "[feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using sendkeys.
  - type: textarea
    attributes:
      label: What feature would you like to see in sendkeys?
      description: Describe the feature and the problem that you would like to see solved.
      placeholder: |
        I would like to be able to ...
        
        So that I can ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Other information:"
      description: |
        Include any other information that may be useful for prioritizing the feature request.
        Examples may include your own proposed solution, other alternatives, references to similar
        features in other tools, or screenshots.
